#lang racket
(require "crear.rkt")
(define (hallarm vec m cont)
  (if (< cont (- (vector-length vec) 1))
      (if (> (vector-ref vec cont) (vector-ref vec m))
          (hallarm vec cont (+ cont 1))
          (hallarm vec m (+ cont 1)))
      m))
(define (mostrar)
  (define n 0)
  (define vec (crear 20 20))
  (printf "El vector generado es el: ~a y el número mayor es ~a" vec (vector-ref vec (hallarm vec 0 0)))
)
(mostrar)
