#lang racket
(define (fibonacci n x y)
  (if (> n 1)
      (begin
        (display x)
        (display "---")
        (displayln y)

        (fibonacci (- n 1) y (+ x y)))
      (display "")))
(define (usar)
  (define x 0)
  (define n 0)
  (define y 0)
  (display "\nFunción para calcular n números de fibonacci.\n¿Cúantos números? ")
  (set! n (read))
  (display "Primer término: ")
  (set! x (read))
  (display "Segundo término: ")
  (set! y (read))
  (fibonacci n x y)
  (usar)
  )
(usar)