#lang racket
(define (Espacios a)
  (if (> a 1)
      (begin
        (display " ")
        (Espacios (- a 1 ))
        )
      (display "")
      )
  )
(define (Principal a e)
  (if (>= a 1)
      (begin
        (Espacios (+ e 1) )
        (display "\\")
        (Espacios (* 2 a))
        (display "/")
        (newline)
        (Principal (- a 1) (+ e 1))
        )
      (display "")
      )
  )
(Principal 15 0)